{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-collateral
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/collateral_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/collateral/collateral_{{ version }}.tar.gz
  sha256: 79c5c8cf8f8ae324d5e993f20e115b50ce29bd8cb336067cc6166be9d57ddff2

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-crayon
    - r-pillar
    - r-purrr
  run:
    - r-base
    - r-crayon
    - r-pillar
    - r-purrr

test:
  commands:
    - $R -e "library('collateral')"           # [not win]
    - "\"%R%\" -e \"library('collateral')\""  # [win]

about:
  home: https://rensa.co/collateral/index.html, https://github.com/rensa/collateral
  license: GPL-3.0-only
  summary: The purrr package allows you to capture the side effects (errors, warning, messages and other output) of functions using safely() and quietly(). Using collateral, you can quickly see which elements of a list (or list-column) returned results, which threw errors and which returned warnings or other output.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
