appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: SUITWgf+xDfE0IJ06+zeEXIVREbZAQ2bNA7uiUnx/7TLu9bqkbvuZyF6sMA0nK2dB7vC1zyQ+KRsU1RF0yut17fsRVEMUHzdvmX8LOh5APYHmvWrvDM48ORO9W6c/eguNW4TGL9hkxWFGkz6DmHKS6illdfMN6PWK2jkQjhV6AqqGhRdi+gIXo+ZKWXIrgGNyxwblQwJHiUAKg15oJtV51r/fMkn/6gbXLVNJ1PVsmIyHtLGlfEw7PxCJZGfoiQU5+jv1RW5/5DIWiV23ygSqvF6L4oEPYuZNyjQg1KrpYLHhx6D2kAXL7x0ES5VTfVMpI2Yk8wM7ZYIbBOVu1wHB075+TBtULOKQWqhFcZdk/7qkoRi9fRkQU2fT5P9tkqmFCQQSK+0OJ9OVbbcDemm+txy8mPUZUXH5goeWc7+R3rcWRdWgiZypPtlPe3MNGNXhMkOA5/0DSAyQylNYa9/3RNzFWftoYMbHBKRJ2Tf4/6p0LFkNOq8OUf/Jc/FLOVz35aFf+0EdBXbaL0yzcSlCbIZbTKdYyFl3ZZv/Ju44/hNWS+BCtqzDlkmd9yb9e+ibtEc9bobQSEn3E6YQpizAny7U7r++rvkXafXmQW1kJvu/xEuXSvEYLu+TSd/EO1oiL5BiMJeteKn0C1gdzbhD/duM6B7azxfySDaHMKbI40=
